### ISSUE TITLE
9-azure-cognitive-services sample changes

### ISSUE THREAD

**Issue by rvinothrajendran** [Azure-Samples/azure-python-labs#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run the sample "“9-azure-cognitive-services"

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10 

### Versions
>2004

### Mention any other details that might be useful
1.	form_recognizer_client.begin_recognize_receipts_from_url(url=url) argument name has to change as **receipt_url=url**

2.	No attribute is available in “receipt” object  
print("Receipt Type: {} has confidence: {}".format(receipt.fields.get("ReceiptType").value, receipt.receipt_type.confidence))
AttributeError: 'RecognizedReceipt' object has no attribute 'receipt_type'
	After the change the code like given below, its working fine
	**receipt_type = receipt.fields.get("ReceiptType")** ( refer the sample here : https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_recognize_receipts_from_url.py)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

cc : @kaerm

**Comment by kaerm** [comment]
Fixed in this PR https://github.com/Azure-Samples/azure-python-labs/pull/15

**Comment by asw101** [comment]
Thank you @rvinothrajendran, we appreciate you picking this up!
