### ISSUE TITLE
Instruction button label incorrect

### ISSUE THREAD

**Issue by crazy4pi314** [Azure-Samples/azure-python-labs#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The instructions for step 2 of this lab https://github.com/Azure-Samples/azure-python-labs/blob/master/9-vscodespaces/README.md#create-a-codespace should reference a button labeled "Create a Codespace"

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by asw101** [comment]
Thank you very much @crazy4pi314! I have just pushed this change now.
