### ISSUE TITLE
Arch Linux: Remote Extension Pack incompatible with VS Code 1.33.1

### ISSUE THREAD

**Issue by kjcole** [Azure-Samples/azure-python-labs#2]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

* Be running a current version of Arch Linux
* Install what is supposedly the latest [Visual Studio Code](https://aur.archlinux.org/packages/visual-studio-code-bin/)  
("Official Binary Version" 1.33.1-1, last updated 2019-04-11 18:56)
* Install the Python extension
* Open Visual Studio Code
* Press `Ctrl-P`
* Paste `ext install ms-vscode-remote.vscode-remote-extensionpack`
* Click `Install` on the newly listed Remote Extension Pack

### Any log messages given by the failure
> `Unable to install because, the extension 'ms-vscode-remote.vscode-remote-extensionpack' compatible with current version '1.33.1' of VS Code is not found.`

### Expected/desired behavior
> No error. Extension installs.

### OS and Version?
> Linux (Arch)

### Versions
> N/A but up-to-date

**Comment by jocassid** [comment]
Ran into same problem on Linux Mint

**Comment by kjcole** [comment]
Oops.  For Arch, The package **MUST** be `visual-studio-code-insiders` **not** `visual-studio-code-bin`. Trying again... And maybe closing this soon.
