### ISSUE TITLE
requests 2.21.0 incompatible with urllib3 1.25.2 (wants an older urllib3)

### ISSUE THREAD

**Issue by kjcole** [Azure-Samples/azure-python-labs#3]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> `curl -L https://aka.ms/InstallAzureCli | bash`

### Any log messages given by the failure
> `ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.`

### Expected/desired behavior
> requests would be in sync with a newer urllib3

### OS and Version?
> Linux (Arch)

### Versions
> N/A. Up-to-date.

**Comment by DADDYBOZO** [comment]
I got exactly same problem when installing requirements file for a user via
=> [pip install -r requirements.txt --user](url)

Effect:
`ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.`

**Comment by asw101** [comment]
Closing as stale. But please re-open if it reoccurs in recent versions.
